version: '2'
services:
  server:
    build: .
    container_name: starket_server
    ports:
      - "8000:8000"
    volumes:
        - /root/starket/stock-simulator-server/mockstarket-front-end:/opt/server/static/
    environment:
      FILE_SERVE: opt/server/static
      #DB_USER: starket
  #db:
   #   image: postgres
   #   restart: always
    #  environment:
     #   POSTGRES_PASSWORD: example
      #  POSTGRES_USER: starket
       # B_PATH: /opt/server/database/
     # volumes:
      #  - ${DB_FOLDER}:/opt/server/database/