version: '3'
services:
  server:
    build: .
    container_name: starket_server
    ports:
      - "8000:8000"
    environment:
      FILE_SERVE: opt/server/static
      DB_USER: starket


  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: example
        POSTGRES_USER: starket

