version: '2'
services:
  server:
    build: .
    container_name: starket_server
    ports:
      - "8000:8000"
    volumes:
        - ${FILE_SERVE}:/opt/server/static/
    environment:
      FILE_SERVE: opt/server/static
      DB_URI: host=db port=5432 user=starket password=password dbname=metrics sslmode=disable
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: starket
      B_PATH: /opt/server/database/
    volumes:
      - ${DB_FOLDER}:/opt/server/database/
